### ISSUE TITLE
AWS Repository Lab 2 Readme not updated, dock image fails

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-productionizing-models-with-sagemaker#1]
Appears the AWS repository for Labs 1,2,3  does not have an updated readme for changes, and the code building the docker image is not working/maintained. (in particular this section: LAB 2: Building the SageMaker TensorFlow Container).

"LAB 2" instructs to use "TensorFlow 1.8.0" however that is not contained within the repository that is referenced, and building 1.14.0 and 1.13.1 fails (COPY failed). Also the directory is different as well.

**Comment by jessepisel** [comment]
thanks for opening this issue :wave:. This notebook is no longer maintained and we will not be updating it any further. I am closing this issue at this time.
